# Generated by Django 4.0 on 2021-12-17 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, height_field=50, null=True, upload_to=users.models.path_avatars_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png'), message="Allowed only ('jpg', 'png')"), users.models.size_image_validator], verbose_name='Аватар', width_field=50),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=150, unique=True, verbose_name='Профиль в соцсети')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='users.myuser', verbose_name='Пользователь')),
            ],
        ),
    ]
